// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD9t6ROVocEcY6ua6DujsvCbtSG3tgp7k',
    appId: '1:826896530498:web:a904f7c892c049b34341db',
    messagingSenderId: '826896530498',
    projectId: 'cooksense-c34d5',
    authDomain: 'cooksense-c34d5.firebaseapp.com',
    storageBucket: 'cooksense-c34d5.firebasestorage.app',
    measurementId: 'G-V8BXTCNCWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRREzZTAsGl7hRkwrMKUoV6w1znaH5IRk',
    appId: '1:826896530498:android:02e148816b57ccf34341db',
    messagingSenderId: '826896530498',
    projectId: 'cooksense-c34d5',
    storageBucket: 'cooksense-c34d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq0Y8ku_GZoy2dJUtpes6_thPz53iaoxI',
    appId: '1:826896530498:ios:9f278206c39e55a44341db',
    messagingSenderId: '826896530498',
    projectId: 'cooksense-c34d5',
    storageBucket: 'cooksense-c34d5.firebasestorage.app',
    androidClientId:
        '826896530498-0qpb1lacule012a6tgl3sg362i6fhu7q.apps.googleusercontent.com',
    iosClientId:
        '826896530498-pk9as8l8c4hqm46kkd2f8jm04235hnos.apps.googleusercontent.com',
    iosBundleId: 'com.sayujsujeev.cooksense',
  );
}
